// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cake.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "ad71f4ec-6358-47a3-8a27-d9dc61d0606b";
        public const string Name = "Cake for Visual Studio 2022";
        public const string Description = @"Adds support for the Cake build tool in Visual Studio 2022. Includes support for the Task Runner Explorer, new templates and bootstrapping important Cake files.";
        public const string Language = "en-US";
        public const string Version = "0.1.1.0";
        public const string Author = "Cake Build";
        public const string Tags = "cake, build";
    }
}
