// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cake.VisualStudio
{
    static class Vsix
    {
        public const string Id = "3cf9b016-d63f-44ee-849d-6f3efc996134";
        public const string Name = "Cake Task Runner";
        public const string Description = "Adds support for Cake build scripts in Visual Studio 2015's Task Runner Explorer.";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Alistair Chapman";
        public const string Tags = "cake, build";
    }
}
